<?php

namespace Proxies\__CG__\Cps\Fludoc\AdmBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Docrec extends \Cps\Fludoc\AdmBundle\Entity\Docrec implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getRemite()
    {
        $this->__load();
        return parent::getRemite();
    }

    public function subirArchivo($directorioDestino)
    {
        $this->__load();
        return parent::subirArchivo($directorioDestino);
    }

    public function PrePersist()
    {
        $this->__load();
        return parent::PrePersist();
    }

    public function PreUpdate()
    {
        $this->__load();
        return parent::PreUpdate();
    }

    public function isFechasOK()
    {
        $this->__load();
        return parent::isFechasOK();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCreadoEl($creadoEl)
    {
        $this->__load();
        return parent::setCreadoEl($creadoEl);
    }

    public function getCreadoEl()
    {
        $this->__load();
        return parent::getCreadoEl();
    }

    public function setRecepcionEl($recepcionEl)
    {
        $this->__load();
        return parent::setRecepcionEl($recepcionEl);
    }

    public function getRecepcionEl()
    {
        $this->__load();
        return parent::getRecepcionEl();
    }

    public function setCite($cite)
    {
        $this->__load();
        return parent::setCite($cite);
    }

    public function getCite()
    {
        $this->__load();
        return parent::getCite();
    }

    public function setFechaDoc($fechaDoc)
    {
        $this->__load();
        return parent::setFechaDoc($fechaDoc);
    }

    public function getFechaDoc()
    {
        $this->__load();
        return parent::getFechaDoc();
    }

    public function setReferencia($referencia)
    {
        $this->__load();
        return parent::setReferencia($referencia);
    }

    public function getReferencia()
    {
        $this->__load();
        return parent::getReferencia();
    }

    public function setInstitucionRem($institucionRem)
    {
        $this->__load();
        return parent::setInstitucionRem($institucionRem);
    }

    public function getInstitucionRem()
    {
        $this->__load();
        return parent::getInstitucionRem();
    }

    public function setPersonaRem($personaRem)
    {
        $this->__load();
        return parent::setPersonaRem($personaRem);
    }

    public function getPersonaRem()
    {
        $this->__load();
        return parent::getPersonaRem();
    }

    public function setCargoRem($cargoRem)
    {
        $this->__load();
        return parent::setCargoRem($cargoRem);
    }

    public function getCargoRem()
    {
        $this->__load();
        return parent::getCargoRem();
    }

    public function setFolio($folio)
    {
        $this->__load();
        return parent::setFolio($folio);
    }

    public function getFolio()
    {
        $this->__load();
        return parent::getFolio();
    }

    public function setArchivo($archivo)
    {
        $this->__load();
        return parent::setArchivo($archivo);
    }

    public function getArchivo()
    {
        $this->__load();
        return parent::getArchivo();
    }

    public function setPin($pin)
    {
        $this->__load();
        return parent::setPin($pin);
    }

    public function getPin()
    {
        $this->__load();
        return parent::getPin();
    }

    public function setModificadoEl($modificadoEl)
    {
        $this->__load();
        return parent::setModificadoEl($modificadoEl);
    }

    public function getModificadoEl()
    {
        $this->__load();
        return parent::getModificadoEl();
    }

    public function setUsuario(\General\ComunBundle\Entity\Usuario $usuario = NULL)
    {
        $this->__load();
        return parent::setUsuario($usuario);
    }

    public function getUsuario()
    {
        $this->__load();
        return parent::getUsuario();
    }

    public function addDerivacione(\Cps\Fludoc\AdmBundle\Entity\Derivacion $derivaciones)
    {
        $this->__load();
        return parent::addDerivacione($derivaciones);
    }

    public function removeDerivacione(\Cps\Fludoc\AdmBundle\Entity\Derivacion $derivaciones)
    {
        $this->__load();
        return parent::removeDerivacione($derivaciones);
    }

    public function getDerivaciones()
    {
        $this->__load();
        return parent::getDerivaciones();
    }

    public function setServicioActual(\General\EmpresaBundle\Entity\Servicio $servicioActual = NULL)
    {
        $this->__load();
        return parent::setServicioActual($servicioActual);
    }

    public function getServicioActual()
    {
        $this->__load();
        return parent::getServicioActual();
    }

    public function setEstadoActual(\General\ComunBundle\Entity\Estado $estadoActual = NULL)
    {
        $this->__load();
        return parent::setEstadoActual($estadoActual);
    }

    public function getEstadoActual()
    {
        $this->__load();
        return parent::getEstadoActual();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'creadoEl', 'recepcionEl', 'cite', 'fechaDoc', 'referencia', 'institucionRem', 'personaRem', 'cargoRem', 'folio', 'archivo', 'pin', 'modificadoEl', 'usuario', 'derivaciones', 'servicioActual', 'estadoActual');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}