<?php

namespace Proxies\__CG__\General\ComunBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Usuario extends \General\ComunBundle\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getUsername()
    {
        $this->__load();
        return parent::getUsername();
    }

    public function isEqualTo(\Symfony\Component\Security\Core\User\UserInterface $usuario)
    {
        $this->__load();
        return parent::isEqualTo($usuario);
    }

    public function eraseCredentials()
    {
        $this->__load();
        return parent::eraseCredentials();
    }

    public function getRoles()
    {
        $this->__load();
        return parent::getRoles();
    }

    public function getSalt()
    {
        $this->__load();
        return parent::getSalt();
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function serialize()
    {
        $this->__load();
        return parent::serialize();
    }

    public function unserialize($data)
    {
        $this->__load();
        return parent::unserialize($data);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function PrePersist()
    {
        $this->__load();
        return parent::PrePersist();
    }

    public function PreUpdate()
    {
        $this->__load();
        return parent::PreUpdate();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setIngresoEl($ingresoEl)
    {
        $this->__load();
        return parent::setIngresoEl($ingresoEl);
    }

    public function getIngresoEl()
    {
        $this->__load();
        return parent::getIngresoEl();
    }

    public function setRetiroEl($retiroEl)
    {
        $this->__load();
        return parent::setRetiroEl($retiroEl);
    }

    public function getRetiroEl()
    {
        $this->__load();
        return parent::getRetiroEl();
    }

    public function setLogin($login)
    {
        $this->__load();
        return parent::setLogin($login);
    }

    public function getLogin()
    {
        $this->__load();
        return parent::getLogin();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function setCreadoEl($creadoEl)
    {
        $this->__load();
        return parent::setCreadoEl($creadoEl);
    }

    public function getCreadoEl()
    {
        $this->__load();
        return parent::getCreadoEl();
    }

    public function setModifiEl($modifiEl)
    {
        $this->__load();
        return parent::setModifiEl($modifiEl);
    }

    public function getModifiEl()
    {
        $this->__load();
        return parent::getModifiEl();
    }

    public function setPerfil(\General\ComunBundle\Entity\Perfil $perfil = NULL)
    {
        $this->__load();
        return parent::setPerfil($perfil);
    }

    public function getPerfil()
    {
        $this->__load();
        return parent::getPerfil();
    }

    public function addAcceso(\General\ComunBundle\Entity\Acceso $accesos)
    {
        $this->__load();
        return parent::addAcceso($accesos);
    }

    public function removeAcceso(\General\ComunBundle\Entity\Acceso $accesos)
    {
        $this->__load();
        return parent::removeAcceso($accesos);
    }

    public function getAccesos()
    {
        $this->__load();
        return parent::getAccesos();
    }

    public function addNoticia(\General\EmpresaBundle\Entity\Noticia $noticias)
    {
        $this->__load();
        return parent::addNoticia($noticias);
    }

    public function removeNoticia(\General\EmpresaBundle\Entity\Noticia $noticias)
    {
        $this->__load();
        return parent::removeNoticia($noticias);
    }

    public function getNoticias()
    {
        $this->__load();
        return parent::getNoticias();
    }

    public function addDocrec(\Cps\Fludoc\AdmBundle\Entity\Docrec $docrecs)
    {
        $this->__load();
        return parent::addDocrec($docrecs);
    }

    public function removeDocrec(\Cps\Fludoc\AdmBundle\Entity\Docrec $docrecs)
    {
        $this->__load();
        return parent::removeDocrec($docrecs);
    }

    public function getDocrecs()
    {
        $this->__load();
        return parent::getDocrecs();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombre', 'ingresoEl', 'retiroEl', 'login', 'password', 'creadoEl', 'modifiEl', 'perfil', 'accesos', 'noticias', 'docrecs');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}